"""
Risk Assessment Pydantic Models for Prithvi Shield.
Defines schemas for AI-powered landslide vulnerability analysis.
"""

from typing import Optional, Union
from enum import Enum
from pydantic import BaseModel, Field


class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    VERY_HIGH = "VERY_HIGH"


class RiskAssessmentRequest(BaseModel):
    """Input parameters for evaluating landslide risk at a specific coordinate."""
    userId: Optional[str] = Field(None, description="Citizen user ID if logged in")
    locationName: Optional[str] = Field(None, examples=["Shimla North Ridge"])
    latitude: float = Field(..., ge=-90.0, le=90.0, examples=[31.1048])
    longitude: float = Field(..., ge=-180.0, le=180.0, examples=[77.1734])
    rainfall: float = Field(..., ge=0.0, description="Cumulative 24-hour rainfall in mm", examples=[120.5])
    slope: float = Field(..., ge=0.0, le=90.0, description="Terrain slope angle in degrees", examples=[38.2])
    elevation: float = Field(..., description="Elevation above sea level in meters", examples=[2205.0])
    soilCondition: str = Field(..., description="Soil classification: saturated, loose, gravel, rocky, clay", examples=["saturated"])
    historicalLandslideActivity: Union[bool, int, str] = Field(
        ...,
        description="Past landslide history (boolean true/false, count integer, or level 'none'/'frequent')",
        examples=[True]
    )


class RiskAssessmentResponse(BaseModel):
    """Output generated by Prithvi Shield risk evaluation engine."""
    assessmentId: str
    userId: Optional[str] = None
    locationName: Optional[str] = None
    latitude: float
    longitude: float
    riskProbability: float = Field(..., description="Calculated probability percentage (0.0% to 100.0%)", examples=[84.2])
    riskLevel: RiskLevel = Field(..., examples=[RiskLevel.HIGH])
    rainfall: float
    slope: float
    elevation: float
    soilCondition: str
    historicalLandslideActivity: str
    createdAt: str
    advisory: str = Field(..., description="Actionable safety guidance for citizen or disaster response authority")
